/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BottlenecksRouteImport } from './routes/bottlenecks'
import { Route as EconomicRouteImport } from './routes/economic'
import { Route as InspectionRouteImport } from './routes/inspection'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as RootCauseRouteImport } from './routes/root-cause'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BottlenecksRoute = BottlenecksRouteImport.update({
  id: '/bottlenecks',
  path: '/bottlenecks',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomicRoute = EconomicRouteImport.update({
  id: '/economic',
  path: '/economic',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionRoute = InspectionRouteImport.update({
  id: '/inspection',
  path: '/inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const RootCauseRoute = RootCauseRouteImport.update({
  id: '/root-cause',
  path: '/root-cause',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bottlenecks': typeof BottlenecksRoute
  '/economic': typeof EconomicRoute
  '/inspection': typeof InspectionRoute
  '/recommendations': typeof RecommendationsRoute
  '/root-cause': typeof RootCauseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bottlenecks': typeof BottlenecksRoute
  '/economic': typeof EconomicRoute
  '/inspection': typeof InspectionRoute
  '/recommendations': typeof RecommendationsRoute
  '/root-cause': typeof RootCauseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bottlenecks': typeof BottlenecksRoute
  '/economic': typeof EconomicRoute
  '/inspection': typeof InspectionRoute
  '/recommendations': typeof RecommendationsRoute
  '/root-cause': typeof RootCauseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bottlenecks'
    | '/economic'
    | '/inspection'
    | '/recommendations'
    | '/root-cause'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bottlenecks'
    | '/economic'
    | '/inspection'
    | '/recommendations'
    | '/root-cause'
  id:
    | '__root__'
    | '/'
    | '/bottlenecks'
    | '/economic'
    | '/inspection'
    | '/recommendations'
    | '/root-cause'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BottlenecksRoute: typeof BottlenecksRoute
  EconomicRoute: typeof EconomicRoute
  InspectionRoute: typeof InspectionRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RootCauseRoute: typeof RootCauseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bottlenecks': {
      id: '/bottlenecks'
      path: '/bottlenecks'
      fullPath: '/bottlenecks'
      preLoaderRoute: typeof BottlenecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economic': {
      id: '/economic'
      path: '/economic'
      fullPath: '/economic'
      preLoaderRoute: typeof EconomicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection': {
      id: '/inspection'
      path: '/inspection'
      fullPath: '/inspection'
      preLoaderRoute: typeof InspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/root-cause': {
      id: '/root-cause'
      path: '/root-cause'
      fullPath: '/root-cause'
      preLoaderRoute: typeof RootCauseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BottlenecksRoute: BottlenecksRoute,
  EconomicRoute: EconomicRoute,
  InspectionRoute: InspectionRoute,
  RecommendationsRoute: RecommendationsRoute,
  RootCauseRoute: RootCauseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
